### PR TITLE
Correctly send on the Transfer-Encoding header in the case of HEAD

### LINKED ISSUE #895: Transfer-Encoding header is incorrect for `HEAD` requests
The bug is that the `Transfer-Encoding` header gets set to the `toString` of the typed header. This is being done [here](https://github.com/http4s/http4s-netty/blob/07e22ca8df43f389a438c5703a41a16350bd9795/core/src/main/scala/org/http4s/netty/NettyModelConversion.scala#L305)

This means the header ends up being set to `Transfer-Encoding(NonEmptyList(TransferCoding(chunked)))`. I have a fix incoming.

### PR DESCRIPTION
**Pull request by coltfred**
Fixes #895.

Checked for other places I could see the misuse of `toString`. The change in `server/src/main/scala/org/http4s/netty/server/ServerNettyModelConversion.scala` wasn't _needed_, but does make it more clear the intention. The change to the ConnHeader line was just because of using the headInstance in a more implicit way.

### CODE REVIEW

**Comment by hamnis** [comment]
This was correct at some point in time, must have been missed when upgrading from 0.21. This must have been there for a long time.

Thanks for spotting and fixing.

File: server/src/test/scala/org/http4s/netty/server/HeaderConversionTest.scala [hunk 1]
```diff
@@ -0,0 +1,161 @@
...
+import org.http4s.netty.client.NettyClientBuilder
+import org.http4s.server.Server
+import org.typelevel.ci._
+
+import java.net.URI
+import java.net.http.HttpClient
+import java.net.http.HttpRequest
+import java.net.http.HttpResponse
+import scala.concurrent.duration._
+import scala.jdk.CollectionConverters._
```
Comment (hamnis) [inline server/src/test/scala/org/http4s/netty/server/HeaderConversionTest.scala:37]: this needs scala-collection-compat for 2.12

Comment (hamnis) [reply server/src/test/scala/org/http4s/netty/server/HeaderConversionTest.scala:37]: should be fine to add that as a test dependency

Comment (coltfred) [reply server/src/test/scala/org/http4s/netty/server/HeaderConversionTest.scala:37]: I forgot that scala 2.12 was a thing. Sorry about that. I'll get it fixed up.

**Comment by hamnis** [comment]
needs `sbt scalafixAll`

**Comment by coltfred** [comment]
Ah, you beat me to it. Thanks!

**Review by hamnis — APPROVED** [review]

**Comment by coltfred** [comment]
@hamnis Thanks for getting this merged. I didn't test main to see if it's still broken there, but I suspect it is. Are you going to get this merged down into there?

**Comment by hamnis** [comment]
main and series/0.7 are probably both probably broken. Will get around to take a look at them this week.
series/0.7 is my main focus at the moment, since that will become the new default branch.

**Comment by coltfred** [comment]
Sounds good. I'll leave it to you. Are you planning on cutting an `0.5` release with this fix? 🙏

**Comment by hamnis** [comment]
yes. Will do that tomorrow. It's almost midnight here in Norway :)

**Comment by hamnis** [comment]
The publish failed, the gpg key has expired. Someone™ is looking into that.
